ACT_HOL_PARTER = 33
CMD_CT = 39
ACT_LIVING = 40
ACT_ATELIER = 42
PMP_PARTER = 43
ACT_ETAJ_BABACI = 44
ACT_FLAVIA_HOL = 45
PMP_ETAJ = 47

ACTUATORS = [ACT_HOL_PARTER, ACT_LIVING, ACT_ATELIER, ACT_ETAJ_BABACI, ACT_FLAVIA_HOL]
PUMPS = [PMP_PARTER, PMP_ETAJ]
